[package]
name = "rasusa"
description = "Randomly subsample reads to a specified coverage"
version = "0.2.0"
authors = ["Michael Hall <michael@mbh.sh>"]
edition = "2018"
repository = "https://github.com/mbhall88/rasusa"
homepage = "https://github.com/mbhall88/rasusa"
readme = "README.md"
keywords = ["bioinformatics", "subsampling", "fastq", "fasta", "coverage"]
categories = ["science", "command-line-utilities"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
travis-ci = { repository = "mbhall88/rasusa" }
codecov = { repository = "mbhall88/rasusa", branch = "master", service = "github" }

[dependencies]
structopt = "0.3.2"
clap = "2.33.0"
regex = "1"
snafu = "0.5.0"
bio = "0.29.0"
failure = "0.1.5"
exitfailure = "0.5.1"
flate2 = "1.0.12"
rand = "0.7.2"
rand_pcg = "0.2.1"
log = "0.4"
fern = { version = "0.5", features = ["colored"] }
chrono = "0.4"
needletail = "0.3.2"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3.1.0"
